{"time":"2025-03-28T02:49:01.0110173-04:00","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"c:\\Users\\Sai\\Documents\\Neu\\Masters_Project\\PerceptionPrivacy\\instance_segmentation\\yolov8-seg\\wandb\\run-20250328_024900-6tg54h4a\\logs\\debug-core.log"}
{"time":"2025-03-28T02:49:01.1208219-04:00","level":"INFO","msg":"created new stream","id":"6tg54h4a"}
{"time":"2025-03-28T02:49:01.1208219-04:00","level":"INFO","msg":"stream: started","id":"6tg54h4a"}
{"time":"2025-03-28T02:49:01.1208219-04:00","level":"INFO","msg":"sender: started","stream_id":"6tg54h4a"}
{"time":"2025-03-28T02:49:01.1208219-04:00","level":"INFO","msg":"handler: started","stream_id":"6tg54h4a"}
{"time":"2025-03-28T02:49:01.1208219-04:00","level":"INFO","msg":"writer: Do: started","stream_id":"6tg54h4a"}
{"time":"2025-03-28T02:49:01.7116397-04:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-03-28T04:08:23.6178394-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.0.0.22:53006->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T04:08:25.8327047-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:08:30.5965051-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:08:34.2525494-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T04:08:36.6816271-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:08:39.0999098-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:08:41.0982843-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:08:50.9857918-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:08:55.4223003-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:09:09.5046551-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:09:34.5557442-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:09:41.6657588-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:12:57.402429-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.0.0.22:62998->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T04:13:14.0876334-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T04:13:25.1682439-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T04:13:49.0958645-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T04:13:59.6138984-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-03-28T04:14:14.5226626-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-28T04:14:20.0945487-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:14:26.5611409-04:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-03-28T04:39:56.4895123-04:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/chainathanss/privacy-segmentation/6tg54h4a/file_stream","body":"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n"}
{"time":"2025-03-28T11:33:45.0971079-04:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-03-28T11:33:45.0983497-04:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-03-28T11:33:46.107286-04:00","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"uploading artifact run-6tg54h4a-curvesRecall-ConfidenceM_table","runtime_seconds":1.0216605}],"total_operations":1}}
{"time":"2025-03-28T11:33:46.2558514-04:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-03-28T11:33:46.6564895-04:00","level":"INFO","msg":"stream: closing","id":"6tg54h4a"}
{"time":"2025-03-28T11:33:46.6564895-04:00","level":"INFO","msg":"handler: closed","stream_id":"6tg54h4a"}
{"time":"2025-03-28T11:33:46.6564895-04:00","level":"INFO","msg":"sender: closed","stream_id":"6tg54h4a"}
{"time":"2025-03-28T11:33:46.6564895-04:00","level":"INFO","msg":"writer: Close: closed","stream_id":"6tg54h4a"}
{"time":"2025-03-28T11:33:46.6604883-04:00","level":"INFO","msg":"stream: closed","id":"6tg54h4a"}
